// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_adminusername_byte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_adminusername_byte));
        
        string IMigrationMetadata.Id
        {
            get { return "202212101612481_mig_adminusername_byte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
